CREATE TABLE [acc].[SubsiVSFId] (
    [SFId] INT IDENTITY (1, 1) NOT NULL,
    [SSId] INT NULL,
    [Fid]  INT NULL,
    CONSTRAINT [PK_SubsiVSFId] PRIMARY KEY CLUSTERED ([SFId] ASC),
    CONSTRAINT [FK_SubsiVSFId_FinAcc] FOREIGN KEY ([Fid]) REFERENCES [acc].[FinAcc] ([Fid]),
    CONSTRAINT [FK_SubsiVSFId_SubsiSetup] FOREIGN KEY ([SSId]) REFERENCES [acc].[SubsiSetup] ([SSId]),
    CONSTRAINT [UQ__SubsiVSF__C1BEAA431076E1DC] UNIQUE NONCLUSTERED ([Fid] ASC)
);

