//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaBase.DAL.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABal
    {
        public long IAccno { get; set; }
        public int FId { get; set; }
        public Nullable<byte> Flag { get; set; }
        public decimal Bal { get; set; }
        public long Id { get; set; }
    }
}
