//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaBase.DAL.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AchqH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AchqH()
        {
            this.AchqHHs = new HashSet<AchqHH>();
        }
    
        public int AchqHId { get; set; }
        public int Rno { get; set; }
        public int ChkNo { get; set; }
        public byte cstate { get; set; }
        public Nullable<long> Tno { get; set; }
    
        public virtual AChq AChq { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AchqHH> AchqHHs { get; set; }
    }
}
