//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaBase.DAL.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AChq
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AChq()
        {
            this.AchqHs = new HashSet<AchqH>();
        }
    
        public int rno { get; set; }
        public int IAccno { get; set; }
        public int cfrom { get; set; }
        public int cto { get; set; }
        public byte cstate { get; set; }
        public int postedby { get; set; }
        public Nullable<int> approvedby { get; set; }
        public System.DateTime tdate { get; set; }
        public Nullable<bool> IsPrinted { get; set; }
    
        public virtual ADetail ADetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AchqH> AchqHs { get; set; }
    }
}
