//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaBase.DAL.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AintCap
    {
        public System.DateTime Vdate { get; set; }
        public int TIaccno { get; set; }
        public int Trxno { get; set; }
        public decimal IntAmt { get; set; }
        public float TaxRt { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> CRamt { get; set; }
        public Nullable<int> FIaccno { get; set; }
        public Nullable<int> Ivno { get; set; }
        public Nullable<int> Tvno { get; set; }
        public Nullable<bool> IsSlf { get; set; }
        public decimal AintCapId { get; set; }
    }
}
