//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaBase.DAL.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AintPayable
    {
        public long Tno { get; set; }
        public System.DateTime Tdate { get; set; }
        public int Iaccno { get; set; }
        public decimal IntAmt { get; set; }
        public float TaxRt { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> CRamt { get; set; }
        public Nullable<decimal> DrAmt { get; set; }
        public Nullable<int> Ivno { get; set; }
        public Nullable<int> Tvno { get; set; }
        public short Valued { get; set; }
        public Nullable<int> PostedBy { get; set; }
        public Nullable<int> VerifiedBy { get; set; }
        public bool ByTeller { get; set; }
        public string Remarks { get; set; }
    
        public virtual ADetail ADetail { get; set; }
    }
}
