//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaBase.DAL.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALCollLand
    {
        public int AcolLandId { get; set; }
        public int Sno { get; set; }
        public string Fname { get; set; }
        public string Gname { get; set; }
        public string Location { get; set; }
        public string Area { get; set; }
        public string Direction { get; set; }
        public string Seatno { get; set; }
        public string Kittano { get; set; }
        public string BArea { get; set; }
    
        public virtual ALColl ALColl { get; set; }
    }
}
