//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaBase.DAL.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALRegistration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ALRegistration()
        {
            this.ALRegCusts = new HashSet<ALRegCust>();
        }
    
        public int RegId { get; set; }
        public int PID { get; set; }
        public decimal LAmt { get; set; }
        public int Duration { get; set; }
        public Nullable<int> ADuration { get; set; }
        public byte Status { get; set; }
        public System.DateTime RegDate { get; set; }
        public Nullable<decimal> SAmt { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> iAccno { get; set; }
        public Nullable<int> PAYSID { get; set; }
        public int PostedBy { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
    
        public virtual ADetail ADetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALRegCust> ALRegCusts { get; set; }
        public virtual ProductDetail ProductDetail { get; set; }
    }
}
