//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaBase.DAL.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AMClearanceHR
    {
        public int rno { get; set; }
        public int IAccno { get; set; }
        public Nullable<short> BrchID { get; set; }
        public short Bankcode { get; set; }
        public short Brnhcode { get; set; }
        public string chqno { get; set; }
        public string payee { get; set; }
        public System.DateTime tdate { get; set; }
        public decimal camount { get; set; }
        public string remarks { get; set; }
        public byte chqpriority { get; set; }
        public short postedby { get; set; }
        public short verifiedby { get; set; }
        public Nullable<byte> chqstate { get; set; }
        public Nullable<short> passedby { get; set; }
        public Nullable<short> collectedby { get; set; }
        public Nullable<System.DateTime> cdate { get; set; }
        public Nullable<short> finalizedby { get; set; }
        public Nullable<System.DateTime> fdate { get; set; }
        public string remarks2 { get; set; }
        public Nullable<int> AVno { get; set; }
        public Nullable<int> RVno { get; set; }
        public Nullable<decimal> tno { get; set; }
        public string ACCNO { get; set; }
    }
}
