//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaBase.DAL.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AMTrn
    {
        public decimal tno { get; set; }
        public int IAccno { get; set; }
        public System.DateTime tdate { get; set; }
        public System.DateTime vdate { get; set; }
        public string notes { get; set; }
        public Nullable<int> slpno { get; set; }
        public decimal dramt { get; set; }
        public decimal cramt { get; set; }
        public int ttype { get; set; }
        public int postedby { get; set; }
        public int approvedby { get; set; }
        public int brnhno { get; set; }
        public Nullable<int> vno { get; set; }
        public bool Isslp { get; set; }
        public Nullable<System.DateTime> PostedOn { get; set; }
    }
}
