//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaBase.DAL.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANominee
    {
        public int NID { get; set; }
        public int IAccno { get; set; }
        public string NomNam { get; set; }
        public string NomRel { get; set; }
        public Nullable<byte> CCertID { get; set; }
        public string CCertno { get; set; }
        public float Share { get; set; }
        public string ContactNo { get; set; }
        public string ContactAddress { get; set; }
    
        public virtual CertificateDef CertificateDef { get; set; }
        public virtual ADetail ADetail { get; set; }
    }
}
