//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaBase.DAL.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AODIntReceivable
    {
        public System.DateTime Tdate { get; set; }
        public int Iaccno { get; set; }
        public decimal DRAmt { get; set; }
        public decimal CRAmt { get; set; }
        public Nullable<int> vno { get; set; }
        public int TType { get; set; }
        public int PostedBy { get; set; }
        public Nullable<int> VerifiedBy { get; set; }
        public string Remarks { get; set; }
        public decimal TNo { get; set; }
    }
}
