//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaBase.DAL.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class APBookChked
    {
        public int ID { get; set; }
        public Nullable<int> IAccNo { get; set; }
        public Nullable<System.DateTime> ChkedOn { get; set; }
        public Nullable<System.DateTime> ChkedTill { get; set; }
        public Nullable<int> ChkedBy { get; set; }
    }
}
