//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaBase.DAL.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASTrn
    {
        public decimal tno { get; set; }
        public int IAccno { get; set; }
        public System.DateTime tdate { get; set; }
        public string notes { get; set; }
        public Nullable<int> slpno { get; set; }
        public decimal dramt { get; set; }
        public decimal cramt { get; set; }
        public byte ttype { get; set; }
        public int postedby { get; set; }
        public int brnhno { get; set; }
        public Nullable<decimal> VNO { get; set; }
        public Nullable<bool> IsSlp { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public System.DateTime PostedOn { get; set; }
    }
}
