//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaBase.DAL.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASTransLoan
    {
        public decimal AstransLoanId { get; set; }
        public decimal tno { get; set; }
        public byte PId { get; set; }
        public decimal Amt { get; set; }
        public Nullable<decimal> vNO { get; set; }
    }
}
