//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaBase.DAL.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AWtdQueue
    {
        public int Rno { get; set; }
        public int IAccno { get; set; }
        public System.DateTime tdate { get; set; }
        public decimal chqno { get; set; }
        public string notes { get; set; }
        public decimal amount { get; set; }
        public Nullable<int> ttype { get; set; }
        public int postedby { get; set; }
        public Nullable<int> Approvedby { get; set; }
        public int BrnhID { get; set; }
        public Nullable<int> currid { get; set; }
        public bool isslip { get; set; }
        public Nullable<decimal> tno { get; set; }
        public byte Qstate { get; set; }
    
        public virtual ADetail ADetail { get; set; }
    }
}
