//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaBase.DAL.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashLimit
    {
        public int cashLimitId { get; set; }
        public int stfid { get; set; }
        public decimal dramt { get; set; }
        public decimal cramt { get; set; }
        public int BranchId { get; set; }
    
        public virtual CashLimit CashLimitS1 { get; set; }
        public virtual CashLimit CashLimit1 { get; set; }
        public virtual Company Company { get; set; }
    }
}
