//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaBase.DAL.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChgMTrnx
    {
        public System.DateTime Tdate { get; set; }
        public int ChgId { get; set; }
        public decimal Amt { get; set; }
        public long TrnxNo { get; set; }
        public string Remarks { get; set; }
        public short Postedby { get; set; }
        public Nullable<short> Approvedby { get; set; }
        public Nullable<int> Iaccno { get; set; }
        public Nullable<short> Vno { get; set; }
        public Nullable<byte> ttype { get; set; }
        public Nullable<decimal> slpno { get; set; }
        public Nullable<decimal> brhid { get; set; }
    }
}
