//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaBase.DAL.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChqAttribute
    {
        public int Id { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string AccountNamePostion { get; set; }
        public string AccountNumberPosition { get; set; }
        public string AccountTypePosition { get; set; }
        public string ChequeNumberPosition { get; set; }
        public string Cheque2NumberPosition { get; set; }
        public string BranchPhoneNumberPosition { get; set; }
        public string BranchNamePosition { get; set; }
        public string BranchAddressPosition { get; set; }
        public string DefaultPrinterName { get; set; }
        public string PaperSize { get; set; }
    }
}
