//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaBase.DAL.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChqInventory
    {
        public int chqInvId { get; set; }
        public int Brnhid { get; set; }
        public decimal FrmChqno { get; set; }
        public decimal Tochqno { get; set; }
        public decimal Lastindx { get; set; }
        public bool ISfinish { get; set; }
        public int PostedBy { get; set; }
        public System.DateTime PostedOn { get; set; }
    }
}
