//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaBase.DAL.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollSheet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CollSheet()
        {
            this.CollSheetTrans = new HashSet<CollSheetTran>();
        }
    
        public long CollSheetId { get; set; }
        public int SheetNo { get; set; }
        public int CollectorId { get; set; }
        public System.DateTime TDate { get; set; }
        public System.DateTime VDate { get; set; }
        public int PostedBy { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public int BrchId { get; set; }
        public decimal TotalAmount { get; set; }
        public string note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CollSheetTran> CollSheetTrans { get; set; }
    }
}
