//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaBase.DAL.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollMainTemp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CollMainTemp()
        {
            this.CollTemps = new HashSet<CollTemp>();
        }
    
        public int RetId { get; set; }
        public int BrchId { get; set; }
        public decimal CollectionAmt { get; set; }
        public int CollectorId { get; set; }
        public System.DateTime TDate { get; set; }
        public System.DateTime VDate { get; set; }
        public int PostedBy { get; set; }
        public decimal TotalAmt { get; set; }
        public int SheetNo { get; set; }
        public Nullable<int> RejectedBy { get; set; }
        public bool Status { get; set; }
        public string RejectedRemarks { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CollTemp> CollTemps { get; set; }
    }
}
