//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaBase.DAL.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.CashLimitS = new HashSet<CashLimit>();
            this.IChkDeps = new HashSet<IChkDep>();
            this.AchqFGdPymts = new HashSet<AchqFGdPymt>();
        }
    
        public int CompanyId { get; set; }
        public string BranchName { get; set; }
        public string Region { get; set; }
        public string State { get; set; }
        public string Address { get; set; }
        public string PhoneNo { get; set; }
        public string Email { get; set; }
        public string FaxNo { get; set; }
        public string Prefix { get; set; }
        public int ParentId { get; set; }
        public Nullable<bool> IsBranch { get; set; }
        public int AdditionalUser { get; set; }
        public string IPAddress { get; set; }
        public Nullable<System.DateTime> TDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashLimit> CashLimitS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IChkDep> IChkDeps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AchqFGdPymt> AchqFGdPymts { get; set; }
    }
}
