//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaBase.DAL.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustContact
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustContact()
        {
            this.CustIRegContacts = new HashSet<CustIRegContact>();
        }
    
        public int CCID { get; set; }
        public decimal CID { get; set; }
        public byte CNotype { get; set; }
        public string CNo { get; set; }
    
        public virtual ContactDef ContactDef { get; set; }
        public virtual CustInfo CustInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustIRegContact> CustIRegContacts { get; set; }
    }
}
