//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaBase.DAL.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustIRegContact
    {
        public int IRCId { get; set; }
        public int CCID { get; set; }
        public decimal CID { get; set; }
    
        public virtual CustContact CustContact { get; set; }
        public virtual CustInfo CustInfo { get; set; }
    }
}
