//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaBase.DAL.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustAddress
    {
        public int CAId { get; set; }
        public Nullable<decimal> CID { get; set; }
        public Nullable<int> LId { get; set; }
        public string BlockNo { get; set; }
        public string StreetNo { get; set; }
        public string OName { get; set; }
        public Nullable<int> ATypeId { get; set; }
    
        public virtual CustInfo CustInfo { get; set; }
        public virtual Location Location { get; set; }
        public virtual LocationTypeDef LocationTypeDef { get; set; }
    }
}
