//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaBase.DAL.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustType()
        {
            this.CustInfoes = new HashSet<CustInfo>();
            this.CustTypeCertificates = new HashSet<CustTypeCertificate>();
            this.CustTypeContacts = new HashSet<CustTypeContact>();
            this.CustTypeSectors = new HashSet<CustTypeSector>();
        }
    
        public byte CtypeID { get; set; }
        public string Ctype { get; set; }
        public byte TaxID { get; set; }
        public byte isind { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustInfo> CustInfoes { get; set; }
        public virtual TaxsetupDef TaxsetupDef { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustTypeCertificate> CustTypeCertificates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustTypeContact> CustTypeContacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustTypeSector> CustTypeSectors { get; set; }
    }
}
