//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaBase.DAL.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustTypeSector
    {
        public int CTSID { get; set; }
        public byte CTypeID { get; set; }
        public short CDepSector { get; set; }
    
        public virtual CustType CustType { get; set; }
        public virtual SectorDef SectorDef { get; set; }
    }
}
