//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaBase.DAL.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustIndividual
    {
        public decimal CID { get; set; }
        public string Fname { get; set; }
        public string Mname { get; set; }
        public string Lname { get; set; }
        public byte Gender { get; set; }
        public short Occpn { get; set; }
        public string GFatherName { get; set; }
        public string FatherName { get; set; }
        public string SpouseName { get; set; }
    
        public virtual CustInfo CustInfo { get; set; }
        public virtual OccupationDef OccupationDef { get; set; }
    }
}
