//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaBase.DAL.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustInfo()
        {
            this.CustAddresses = new HashSet<CustAddress>();
            this.CustCertificates = new HashSet<CustCertificate>();
            this.CustContacts = new HashSet<CustContact>();
            this.CustContactPersons = new HashSet<CustContactPerson>();
            this.AOfCusts = new HashSet<AOfCust>();
            this.CustIRegContacts = new HashSet<CustIRegContact>();
        }
    
        public decimal CID { get; set; }
        public byte CtypeID { get; set; }
        public short CDepSector { get; set; }
        public System.DateTime CRegdate { get; set; }
        public byte CCCertID { get; set; }
        public string CCCertno { get; set; }
        public Nullable<bool> IsIncomplete { get; set; }
        public Nullable<System.DateTime> DoB { get; set; }
        public Nullable<int> Postedby { get; set; }
        public Nullable<int> Appby { get; set; }
        public string PANNo { get; set; }
        public string Street { get; set; }
    
        public virtual CertificateDef CertificateDef { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustAddress> CustAddresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustCertificate> CustCertificates { get; set; }
        public virtual CustCompany CustCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustContact> CustContacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustContactPerson> CustContactPersons { get; set; }
        public virtual CustIndividual CustIndividual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AOfCust> AOfCusts { get; set; }
        public virtual CustInfo CustInfo1 { get; set; }
        public virtual CustInfo CustInfo2 { get; set; }
        public virtual CustType CustType { get; set; }
        public virtual SectorDef SectorDef { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustIRegContact> CustIRegContacts { get; set; }
    }
}
