//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaBase.DAL.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisburseCheque
    {
        public int DisChequeId { get; set; }
        public int DisburseId { get; set; }
        public string ChequeNo { get; set; }
        public int BankId { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual DisbursementMain DisbursementMain { get; set; }
    }
}
