//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaBase.DAL.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisburseCharge
    {
        public int DisChargeId { get; set; }
        public Nullable<int> DisburseId { get; set; }
        public Nullable<int> FID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> IAccno { get; set; }
        public Nullable<int> Vno { get; set; }
        public string Remarks { get; set; }
    
        public virtual DisbursementMain DisbursementMain { get; set; }
    }
}
