//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaBase.DAL.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeVsBranch
    {
        public int MapId { get; set; }
        public int BranchId { get; set; }
        public int EmpId { get; set; }
        public System.DateTime StartFrom { get; set; }
        public int PostedBy { get; set; }
        public System.DateTime PostedOn { get; set; }
        public int CurrentRole { get; set; }
    }
}
