//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaBase.DAL.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinSys2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FinSys2()
        {
            this.FinAccs = new HashSet<FinAcc>();
        }
    
        public int F2id { get; set; }
        public int F1id { get; set; }
        public string F2Desc { get; set; }
        public Nullable<int> Pid { get; set; }
        public int F1Type { get; set; }
        public bool IsFixed { get; set; }
        public int Count { get; set; }
        public byte[] Content { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinAcc> FinAccs { get; set; }
        public virtual FinSys1 FinSys1 { get; set; }
    }
}
