//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaBase.DAL.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FrxCurrencyRate
    {
        public byte TmpId { get; set; }
        public int CurrID { get; set; }
        public decimal BSPerUnit { get; set; }
        public decimal Brate { get; set; }
        public decimal Srate { get; set; }
        public Nullable<decimal> Mrate { get; set; }
    
        public virtual CurrencyType CurrencyType { get; set; }
    }
}
