//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaBase.DAL.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guarantor
    {
        public int GId { get; set; }
        public int LIaccno { get; set; }
        public int GIaccno { get; set; }
        public Nullable<decimal> BlockedAmt { get; set; }
        public bool DisplayMsg { get; set; }
        public bool IsPercent { get; set; }
        public bool Status { get; set; }
        public int PostedBy { get; set; }
        public System.DateTime PostedOn { get; set; }
        public Nullable<int> Sno { get; set; }
    
        public virtual ADetail ADetail { get; set; }
    }
}
