//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaBase.DAL.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HADRenew
    {
        public int ID { get; set; }
        public Nullable<int> IAccNo { get; set; }
        public Nullable<int> DurationId { get; set; }
        public Nullable<System.DateTime> ValDate { get; set; }
        public Nullable<System.DateTime> MatDate { get; set; }
        public Nullable<int> IntCalcRule { get; set; }
        public Nullable<int> IntCaptDur { get; set; }
        public Nullable<decimal> IntRate { get; set; }
        public Nullable<decimal> AgrAmt { get; set; }
        public Nullable<System.DateTime> RNDate { get; set; }
        public Nullable<int> Basic { get; set; }
    }
}
