//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaBase.DAL.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HALRenew
    {
        public int ID { get; set; }
        public Nullable<int> IAccNo { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<System.DateTime> StDate { get; set; }
        public Nullable<System.DateTime> MDate { get; set; }
        public Nullable<int> PSID { get; set; }
        public Nullable<int> PF { get; set; }
        public Nullable<int> IF { get; set; }
        public Nullable<int> GMonthP { get; set; }
        public Nullable<int> GMonthI { get; set; }
        public Nullable<int> GDayP { get; set; }
        public Nullable<int> GDayI { get; set; }
        public Nullable<System.DateTime> GDateP { get; set; }
        public Nullable<System.DateTime> GDateI { get; set; }
        public Nullable<int> Days { get; set; }
        public Nullable<int> PMI { get; set; }
        public Nullable<float> Rate { get; set; }
        public Nullable<System.DateTime> RNDate { get; set; }
        public Nullable<int> Flag { get; set; }
    }
}
