//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaBase.DAL.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class IChkDep
    {
        public long Tno { get; set; }
        public int FIaccno { get; set; }
        public int TIAccno { get; set; }
        public System.DateTime Tdate { get; set; }
        public Nullable<System.DateTime> Vdate { get; set; }
        public decimal Amt { get; set; }
        public int Ttype { get; set; }
        public int SlpNo { get; set; }
        public int postedby { get; set; }
        public Nullable<int> verifiedby { get; set; }
        public Nullable<int> Vno { get; set; }
        public Nullable<decimal> AVno { get; set; }
        public Nullable<bool> IBChq { get; set; }
        public int BrchID { get; set; }
    
        public virtual ADetail ADetail { get; set; }
        public virtual ADetail ADetail1 { get; set; }
        public virtual Company Company { get; set; }
    }
}
