//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaBase.DAL.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicenseBranch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LicenseBranch()
        {
            this.RemitDeposits = new HashSet<RemitDeposit>();
            this.RemitPayments = new HashSet<RemitPayment>();
        }
    
        public int BrnhID { get; set; }
        public string BrnhNam { get; set; }
        public string Addr { get; set; }
        public Nullable<short> RegID { get; set; }
        public string State { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string IPAdd { get; set; }
        public Nullable<short> PBrnhID { get; set; }
        public Nullable<byte> ExtraUsrNo { get; set; }
        public string Prefix { get; set; }
        public int CalSID { get; set; }
        public int CalCid { get; set; }
        public System.DateTime TDate { get; set; }
        public bool UseLimit { get; set; }
        public bool atclosing { get; set; }
        public Nullable<System.DateTime> MigDate { get; set; }
        public string CleCode { get; set; }
        public Nullable<byte> inExpMode { get; set; }
        public Nullable<decimal> Floint { get; set; }
        public bool IsCalcIOnI { get; set; }
        public int schprovdys { get; set; }
        public Nullable<int> FYID { get; set; }
    
        public virtual LicenseRegion LicenseRegion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RemitDeposit> RemitDeposits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RemitPayment> RemitPayments { get; set; }
    }
}
