//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaBase.DAL.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessInfo
    {
        public int Id { get; set; }
        public int EventValue { get; set; }
        public byte Idtype { get; set; }
        public byte Eventid { get; set; }
        public System.DateTime Fdate { get; set; }
        public System.DateTime Tdate { get; set; }
        public string Mdesc { get; set; }
    }
}
