//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaBase.DAL.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobileBanking
    {
        public long Tno { get; set; }
        public System.DateTime TDate { get; set; }
        public int IAccNO { get; set; }
        public int TType { get; set; }
        public string MobileNo { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime PostedOn { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> SuccessOrFailureOn { get; set; }
        public Nullable<int> Vno { get; set; }
    }
}
