//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaBase.DAL.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCollateralDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NCollateralDetail()
        {
            this.ALColls = new HashSet<ALColl>();
        }
    
        public int NCId { get; set; }
        public string Collateral { get; set; }
        public string NrbNo { get; set; }
        public Nullable<int> pNCId { get; set; }
        public bool nodeType { get; set; }
        public bool IsActive { get; set; }
        public string Alias { get; set; }
        public string hId { get; set; }
        public Nullable<int> Pid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALColl> ALColls { get; set; }
    }
}
