//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaBase.DAL.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolicyIntCalc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PolicyIntCalc()
        {
            this.ProductOPSIDs = new HashSet<ProductOPSID>();
            this.ProductPSIDs = new HashSet<ProductPSID>();
        }
    
        public byte PSID { get; set; }
        public string PSName { get; set; }
        public byte RID { get; set; }
        public byte BALID { get; set; }
        public byte DURID { get; set; }
    
        public virtual RuleBalance RuleBalance { get; set; }
        public virtual RuleDuration RuleDuration { get; set; }
        public virtual RuleRate RuleRate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductOPSID> ProductOPSIDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductPSID> ProductPSIDs { get; set; }
    }
}
