//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaBase.DAL.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTID
    {
        public int PFIID { get; set; }
        public int PID { get; set; }
        public byte TID { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<bool> Flag { get; set; }
    
        public virtual ProductDetail ProductDetail { get; set; }
        public virtual TempIntRate TempIntRate { get; set; }
    }
}
