//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaBase.DAL.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPCID
    {
        public int PPCId { get; set; }
        public int PID { get; set; }
        public byte PCID { get; set; }
        public byte IsDefault { get; set; }
    
        public virtual PolicyPenCalc PolicyPenCalc { get; set; }
        public virtual ProductDetail ProductDetail { get; set; }
    }
}
