//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaBase.DAL.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductICBDur
    {
        public int PICBDurID { get; set; }
        public int PID { get; set; }
        public byte ICBDurID { get; set; }
        public Nullable<float> IRate { get; set; }
        public bool IsDefault { get; set; }
    
        public virtual ProductDetail ProductDetail { get; set; }
        public virtual RuleICBDuration RuleICBDuration { get; set; }
    }
}
