//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaBase.DAL.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCurrency
    {
        public int PID { get; set; }
        public short BrchID { get; set; }
        public short CurrID { get; set; }
        public bool DefCurr { get; set; }
    
        public virtual ProductDetail ProductDetail { get; set; }
    }
}
