//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaBase.DAL.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductVfin
    {
        public int ID { get; set; }
        public Nullable<int> PID { get; set; }
        public Nullable<int> FID { get; set; }
        public Nullable<int> F1id { get; set; }
        public Nullable<int> CurrId { get; set; }
    
        public virtual FinAcc FinAcc { get; set; }
        public virtual ProductDetail ProductDetail { get; set; }
    }
}
