//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaBase.DAL.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferenceInfo
    {
        public int RIId { get; set; }
        public int IAccNo { get; set; }
        public int ReferredBy { get; set; }
        public int BroughtBy { get; set; }
        public Nullable<byte> RType { get; set; }
    
        public virtual ADetail ADetail { get; set; }
    }
}
