//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaBase.DAL.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemitDeposit
    {
        public int RemitDepositId { get; set; }
        public decimal Tno { get; set; }
        public string SenderName { get; set; }
        public string SenderContact { get; set; }
        public int RemitCompanyId { get; set; }
        public decimal Amount { get; set; }
        public string Remarks { get; set; }
        public int PostedBy { get; set; }
        public System.DateTime PostedOn { get; set; }
        public Nullable<int> ApproveBy { get; set; }
        public Nullable<System.DateTime> ApproveOn { get; set; }
        public int BranchId { get; set; }
        public Nullable<decimal> Vno { get; set; }
        public string ReceiverName { get; set; }
        public string ReceiverAddress { get; set; }
        public string ReceiverContact { get; set; }
    
        public virtual RemittanceCustomer RemittanceCustomer { get; set; }
        public virtual LicenseBranch LicenseBranch { get; set; }
    }
}
