//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaBase.DAL.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchemeVFin
    {
        public int ID { get; set; }
        public Nullable<byte> SDID { get; set; }
        public Nullable<int> FID { get; set; }
        public Nullable<int> F1Id { get; set; }
        public Nullable<int> IsLocal { get; set; }
    
        public virtual FinAcc FinAcc { get; set; }
        public virtual SchmDetail SchmDetail { get; set; }
    }
}
