//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaBase.DAL.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchmDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SchmDetail()
        {
            this.ProductDetails = new HashSet<ProductDetail>();
        }
    
        public byte SDID { get; set; }
        public int FID { get; set; }
        public string SDName { get; set; }
        public bool HasDuration { get; set; }
        public bool HasOverdraw { get; set; }
        public bool HasCheque { get; set; }
        public bool HasCard { get; set; }
        public bool HasCertificate { get; set; }
        public bool HasIndivLimit { get; set; }
        public bool HasIndivRate { get; set; }
        public bool HasDormancy { get; set; }
        public bool IsRenewable { get; set; }
        public byte SType { get; set; }
        public bool SEnable { get; set; }
        public Nullable<byte> ICBID { get; set; }
        public Nullable<byte> MID { get; set; }
        public Nullable<bool> Revolving { get; set; }
        public bool Nomianable { get; set; }
        public Nullable<bool> MultiDeposit { get; set; }
        public Nullable<bool> Withdrawal { get; set; }
        public Nullable<bool> IsInsured { get; set; }
        public Nullable<bool> HASSMS { get; set; }
        public Nullable<bool> IsFDLoan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductDetail> ProductDetails { get; set; }
        public virtual RuleICB RuleICB { get; set; }
        public virtual RuleMovement RuleMovement { get; set; }
        public virtual FinAcc FinAcc { get; set; }
    }
}
