//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaBase.DAL.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCrtDtl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SCrtDtl()
        {
            this.ShrPurchases = new HashSet<ShrPurchase>();
        }
    
        public decimal Sid { get; set; }
        public decimal SCrtno { get; set; }
        public decimal FSno { get; set; }
        public decimal TSno { get; set; }
        public decimal SQty { get; set; }
        public int Status { get; set; }
        public byte Stype { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShrPurchase> ShrPurchases { get; set; }
    }
}
