//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaBase.DAL.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SheetNo
    {
        public int UTId { get; set; }
        public int FYId { get; set; }
        public string TransType { get; set; }
        public int BranchId { get; set; }
        public int CurrentNo { get; set; }
    }
}
