//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaBase.DAL.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShrReg
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShrReg()
        {
            this.ShrPurchases = new HashSet<ShrPurchase>();
            this.ShrSPurchases = new HashSet<ShrSPurchase>();
            this.Snominees = new HashSet<Snominee>();
            this.ShareReferenceInfoes = new HashSet<ShareReferenceInfo>();
        }
    
        public decimal CId { get; set; }
        public decimal RegNo { get; set; }
        public Nullable<System.DateTime> Rdate { get; set; }
        public int PostedBy { get; set; }
        public int ApprovedBy { get; set; }
        public string RegistrationCode { get; set; }
        public Nullable<System.DateTime> PostedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShrPurchase> ShrPurchases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShrSPurchase> ShrSPurchases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Snominee> Snominees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShareReferenceInfo> ShareReferenceInfoes { get; set; }
    }
}
