//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannakyaBase.DAL.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmEditLog
    {
        public int EditID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public int Iaccno { get; set; }
        public string Value { get; set; }
        public System.DateTime Tdate { get; set; }
        public Nullable<decimal> Tno { get; set; }
        public int BrnchID { get; set; }
        public Nullable<int> PostedBy { get; set; }
        public Nullable<System.DateTime> PostedOn { get; set; }
        public Nullable<short> Status { get; set; }
        public Nullable<System.DateTime> VerifiedOn { get; set; }
        public Nullable<int> VerifiedBy { get; set; }
        public Nullable<System.DateTime> RejectedOn { get; set; }
        public Nullable<int> RejectedBy { get; set; }
    }
}
