CREATE TABLE [fin].[ALoan] (
    [IAccno]                    INT             NOT NULL,
    [PAYID]                     TINYINT         NOT NULL,
    [PAYSID]                    TINYINT         NOT NULL,
    [PFreq]                     INT             NOT NULL,
    [IFreq]                     INT             NOT NULL,
    [cDay]                      TINYINT         NULL,
    [overPay]                   BIT             NOT NULL,
    [OthrBal]                   NUMERIC (19, 2) NULL,
    [IonPA]                     NUMERIC (19, 2) NULL,
    [IonPR]                     NUMERIC (19, 2) NULL,
    [IonCA]                     NUMERIC (19, 2) NULL,
    [IonCR]                     NUMERIC (19, 2) NULL,
    [PonPrA]                    NUMERIC (19, 2) NULL,
    [PonPrR]                    NUMERIC (19, 2) NULL,
    [PonIA]                     NUMERIC (19, 2) NULL,
    [PonIR]                     NUMERIC (19, 2) NULL,
    [IonIR]                     NUMERIC (19, 2) NULL,
    [IonIA]                     NUMERIC (19, 2) NULL,
    [IsInsured]                 BIT             NOT NULL,
    [AutoPayment]               BIT             CONSTRAINT [DF_ALoan_AutoPayment] DEFAULT ((0)) NOT NULL,
    [penGDys]                   SMALLINT        NULL,
    [Revolving]                 BIT             CONSTRAINT [DF_ALoan_Revolving] DEFAULT ((0)) NULL,
    [deprived]                  BIT             NULL,
    [PostedBy]                  INT             NOT NULL,
    [PostedOn]                  DATETIME        CONSTRAINT [DF_ALoan_PostedOn] DEFAULT (getdate()) NOT NULL,
    [ApprovedBy]                INT             NULL,
    [ApprovedOn]                DATETIME        NULL,
    [PrincipleLoanOut]          MONEY           NULL,
    [OtherLoanOut]              MONEY           NULL,
    [IsChargeOnSancation]       BIT             NULL,
    [LastTotalInterestPaidDate] DATE            NULL,
    CONSTRAINT [PK_ALoan] PRIMARY KEY CLUSTERED ([IAccno] ASC),
    CONSTRAINT [FK_ALoan_ADetail] FOREIGN KEY ([IAccno]) REFERENCES [fin].[ADetail] ([IAccno])
);

