CREATE TABLE [fin].[LicenseBranch] (
    [BrnhID]     INT             IDENTITY (1, 1) NOT NULL,
    [BrnhNam]    NVARCHAR (MAX)  NULL,
    [Addr]       NVARCHAR (MAX)  NULL,
    [RegID]      SMALLINT        NULL,
    [State]      NVARCHAR (MAX)  NULL,
    [Phone]      NVARCHAR (MAX)  NULL,
    [Fax]        NVARCHAR (MAX)  NULL,
    [Email]      NVARCHAR (MAX)  NULL,
    [IPAdd]      NVARCHAR (MAX)  NULL,
    [PBrnhID]    SMALLINT        NULL,
    [ExtraUsrNo] TINYINT         NULL,
    [Prefix]     NVARCHAR (MAX)  NULL,
    [CalSID]     INT             NOT NULL,
    [CalCid]     INT             NOT NULL,
    [TDate]      DATETIME        NOT NULL,
    [UseLimit]   BIT             NOT NULL,
    [atclosing]  BIT             NOT NULL,
    [MigDate]    DATETIME        NULL,
    [CleCode]    NVARCHAR (MAX)  NULL,
    [inExpMode]  TINYINT         NULL,
    [Floint]     DECIMAL (18, 2) NULL,
    [IsCalcIOnI] BIT             NOT NULL,
    [schprovdys] INT             NOT NULL,
    [FYID]       INT             NULL,
    CONSTRAINT [PK_fin.LicenseBranch] PRIMARY KEY CLUSTERED ([BrnhID] ASC),
    CONSTRAINT [FK_LicenseBranch_LicenseRegion] FOREIGN KEY ([RegID]) REFERENCES [dbo].[LicenseRegion] ([RegID])
);

