CREATE TABLE [fin].[ProductDetail] (
    [SDID]           TINYINT       NOT NULL,
    [PID]            INT           IDENTITY (1, 1) NOT NULL,
    [FID]            INT           NOT NULL,
    [PName]          VARCHAR (100) NOT NULL,
    [Duration]       REAL          NULL,
    [HasOverdraw]    BIT           NOT NULL,
    [HasCheque]      BIT           NOT NULL,
    [HasCard]        BIT           NOT NULL,
    [HasCertificate] BIT           NOT NULL,
    [HasIndivLimit]  BIT           NULL,
    [HasIndDuration] BIT           CONSTRAINT [DF_ProductDetail_HasIndDuration] DEFAULT ((0)) NULL,
    [DormantPeriod]  TINYINT       NULL,
    [HasIndivRate]   BIT           NULL,
    [IRate]          REAL          NULL,
    [OIRate]         REAL          NULL,
    [PPRate]         REAL          NULL,
    [PIRate]         REAL          NULL,
    [MID]            TINYINT       NOT NULL,
    [RNWID]          TINYINT       NULL,
    [LAmt]           MONEY         NOT NULL,
    [PGRACE]         REAL          NULL,
    [ODuration]      REAL          NULL,
    [Nomianable]     BIT           NOT NULL,
    [enabled]        BIT           NOT NULL,
    [MultiDep]       BIT           NULL,
    [Withdrawal]     BIT           NULL,
    [IntraBrnhTrnx]  BIT           NULL,
    [Apfix]          NVARCHAR (50) NULL,
    [aCtr]           NUMERIC (18)  NULL,
    [IsInsured]      BIT           NOT NULL,
    [NSId]           INT           NULL,
    [Schedule]       BIT           NULL,
    [penGDys]        SMALLINT      NULL,
    [durState]       TINYINT       NULL,
    [Revolving]      BIT           NULL,
    [HASSMS]         BIT           NULL,
    CONSTRAINT [PK_ProductDetail] PRIMARY KEY CLUSTERED ([PID] ASC),
    CONSTRAINT [FK_ProductDetail_FinAcc1] FOREIGN KEY ([FID]) REFERENCES [acc].[FinAcc] ([Fid]),
    CONSTRAINT [FK_ProductDetail_RuleRenew] FOREIGN KEY ([RNWID]) REFERENCES [fin].[RuleRenew] ([RNWID]),
    CONSTRAINT [FK_ProductDetail_SchmDetails] FOREIGN KEY ([SDID]) REFERENCES [fin].[SchmDetails] ([SDID])
);

