CREATE TABLE [fin].[SchmDetails] (
    [SDID]           TINYINT       IDENTITY (1, 1) NOT NULL,
    [FID]            INT           NOT NULL,
    [SDName]         NVARCHAR (65) NOT NULL,
    [HasDuration]    BIT           NOT NULL,
    [HasOverdraw]    BIT           NOT NULL,
    [HasCheque]      BIT           NOT NULL,
    [HasCard]        BIT           NOT NULL,
    [HasCertificate] BIT           NOT NULL,
    [HasIndivLimit]  BIT           NOT NULL,
    [HasIndivRate]   BIT           NOT NULL,
    [HasDormancy]    BIT           NOT NULL,
    [IsRenewable]    BIT           NOT NULL,
    [SType]          TINYINT       NOT NULL,
    [SEnable]        BIT           NOT NULL,
    [ICBID]          TINYINT       NULL,
    [MID]            TINYINT       NULL,
    [Revolving]      BIT           NULL,
    [Nomianable]     BIT           NOT NULL,
    [MultiDeposit]   BIT           NULL,
    [Withdrawal]     BIT           NULL,
    [IsInsured]      BIT           NULL,
    [HASSMS]         BIT           NULL,
    [IsFDLoan]       BIT           NULL,
    CONSTRAINT [PK_SchmDetails] PRIMARY KEY CLUSTERED ([SDID] ASC),
    CONSTRAINT [FK_SchmDetails_FinAcc] FOREIGN KEY ([FID]) REFERENCES [acc].[FinAcc] ([Fid]),
    CONSTRAINT [FK_SchmDetails_RuleICB] FOREIGN KEY ([ICBID]) REFERENCES [fin].[RuleICB] ([ICBID]),
    CONSTRAINT [FK_SchmDetails_RuleMovement] FOREIGN KEY ([MID]) REFERENCES [fin].[RuleMovement] ([MID])
);

